spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: localhost
        password: pearl2044
        url: jdbc:mysql://localhost:3306/study_db
    jpa:
        database: mysql
        hibernate:
            ddl-auto: create-drop
        generate-ddl: true
        properties:
            hibernate:
                format_sql: true
                enable_lazy_load_no_trans: true